name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"  # Every day at 6 AM IST
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📊 Generate Metrics (fast mode)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          output_action: commit
          base: header, activity
          plugin_languages: yes
