name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📊 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          user: Praveen-C05
          template: terminal
          base: header, activity, community, repositories, metadata

          config_timezone: Asia/Kolkata
          config_twemoji: yes
          config_display: large
          config_animations: yes
          config_padding: 8%, 5%

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, projects, editors

          plugin_stackoverflow: yes
          plugin_stackoverflow_user: your_so_user_id
          plugin_stackoverflow_sections: answers-top, questions-recent

          plugin_leetcode: yes
          plugin_leetcode_user: your_leetcode_username
          plugin_leetcode_sections: solved, recent

          plugin_16personalities: yes
          plugin_16personalities_url: https://www.16personalities.com/profiles/your_profile_id

          output_action: commit
          output_condition: always
