name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:       # Manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📊 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          # 👇 Personal access token stored in GitHub secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # 👇 This is what you're missing!
          committer_token: ${{ secrets.METRICS_TOKEN }}

          user: Praveen-C05
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

          # Enables commit of metrics.svg
          output_action: commit
          output_commit_message: "📊 Update GitHub metrics"
