name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📊 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: Praveen-C05

          # Display
          template: classic
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          config_octicon: yes
          config_animations: yes
          config_display: large
          config_output: svg
          config_order: base.header, isocalendar, languages, habits, stars, topics, activity, achievements, notable, people

          # Base sections
          base: header, activity, community, repositories, metadata

          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_lines: yes
          plugin_followup: yes
          plugin_stargazers: yes
          plugin_repositories: yes
          plugin_topics: yes
          plugin_people: yes
          plugin_isocalendar: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: your_stackoverflow_id
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_16personalities: yes
          plugin_16personalities_url: https://www.16personalities.com/profiles/your-profile-id

          # Output
          output_action: commit
          filename: github-metrics.svg
