name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"  # Daily at 6 AM IST
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📊 Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          output_action: none  # Don't auto-commit; we'll do it manually
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_activity: yes
          plugin_traffic: yes

      - name: 🚀 Move Metrics to Root
        run: |
          cp github-metrics.svg $GITHUB_WORKSPACE/github-metrics.svg

      - name: 📤 Commit and Push Metrics
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add github-metrics.svg
          git commit -m "📈 Update GitHub Metrics" || echo "No changes to commit"
          git push
