name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 📊 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          user: Praveen-C05
          template: terminal
          config_display: large
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          config_octicon: yes
          config_order: base.header, base.repositories, isocalendar, languages, wakatime, achievements, activity, habits, followup, notable, people, stargazers

          # Plugins
          base: header, repositories
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_lines: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_wakatime: yes
          wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
