name: 📊 Generate GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📊 Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          output_action: commit
          config_timezone: Asia/Kolkata

          base: header, activity, community, repositories, metadata

          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_isocalendar: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_nightscout: yes
          plugin_wakatime: yes
          wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_visitors: yes
          plugin_stars: yes
