name: 📊 Generate GitHub Metrics
on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 📊 Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Praveen-C05

          # Plugins
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_order: base, isocalendar, languages, habits, stargazers
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_skipped: ""
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_stargazers: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: false
          plugin_lines: yes
          plugin_traffic: yes

          # Visitors (enabled by default with classic token)
          plugin_followup: yes

          # Optional: WakaTime plugin (only if you set token)
          plugin_wakatime: yes
          wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
